language: node_js
node_js:
   - "0.8"
before_install:
   - "npm install -g hexo"
   - "ls"
   - "hexo version"
before_script:
   - git config --global user.name "shuenhoy"
   - git config --global user.email "shuenhoy@gmail.com"
   - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
   - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
   - chmod 600 ~/.ssh/id_rsa
   - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


script:
   - "curl -o /usr/lib/node_modules/hexo/lib/model.js https://gist.github.com/Shuenhoy/6039360/raw/ab01e9aaa61f6db5639967b3db1b668504906678/model.js"
   - "curl -o /usr/lib/node_modules/hexo/lib/ChinesePY.js https://gist.github.com/Shuenhoy/6039380/raw/d935a140e3f1dcd8b1ea2f526fac71b43fa72412/ChinesePY"
   - "curl -o /usr/lib/node_modules/hexo/lib/plugins/deployer https://gist.github.com/Shuenhoy/6039407/raw/26785b478179d6b45ca2854629431f3cdeb1f9a4/github.js"
   - "hexo generate"

after_script:
   - "hexo deploy" 
env:
   global:
      - REPO="git@github.com:shuenhoy/blog_source"
      - secure: "IOgHjzgGXnSxrXcjdQIaQLPnfy4M6hzC7IwK69NS/I6eRVXd/AePqQtYYe8C2ThhaRAbieBsptRayX0MdTG3VRzYPYup2m8pUFHy+x0iuxtFNcyRp+XrOgEPChCq/CUfli3fVy3hgy/KiAqyyR0IUtSQ9aDQGVJw4EZjLqIzR6w="
      - secure: "J0OKlDAIF+1GGuWxNow4OaFMu7ZjJDdoe9qJkSDmskKwklv4Jhg+SdJ0kHA3YX5gIIU8oGDVAUmjES58672PbMccrvTMXpxr/WBWU5Aln0mKZvkS1+mg4aQ2qFhE+TAguteutvG2/eQHECFDlm+awcHPdwglNsS5ZN3/aNM+ZfA="
      - secure: "jOE8jt4+22C0KYqylU0ANKzGtZhZPG2TMdxLdmhN9xT1UiL1Add6PNzNxxPx+xw40VhWbJOkCYIu6koRHoXwcNCd+ILNHkDX6ZtQj+C3vlmGJtQaBa4NDIbeKK5Zfc93Q4oeX514qCZzEY47VM3CHj91BQ2L5TwpQ91TqiqKqUY="
      - secure: "C6kyJp6nhGws0g7LTzPSXVmGyfPVBX3vObemsAcrHRTcWVP56NocehQrYnOX+lrXr6ljCMZY2puQGA29h65lYuwq1RvViM+dVHyck67YIanaBrRTBnI9qrSAfaJQ3z3jq43FLNupozOlyyZXE1rAGiAPSc5q0WEbGoLgLmPuk08="
      - secure: "Be5HuTUdwsetN0I6IRQIm7cWtoCn4KukdRe4odouFepKxM1MlIaJ4zT5ed8iQ7ioKsZiwpq4iJs+8JMRZre4g3EvlrqQTvNKW6so4Iu94RPkOZ9TNE3JAnEGkEpHNSwIZtq+yqBQYxzm0+VWC/g8m7Nhx3Cd9mTvgEPO2FTBVx4="
      - secure: "hL80gVbZRp3PYSCt/fI3VFyG3k6KswmL4YB7vJYFEFdx733U4jnVKc4RzJPu+NSK22MEbFauvYMTRPwEFOCyGoJvHIqyIqVx2PwoO4Uof80Jwa4ZfyHM9U0rgw7ssP4/VMsVxpRyIMkgExEXPDUddgG3jS/T0yk6SdBRJiSkApc="
      - secure: "gY5kagJRTjxHRggyobcB1yABNCxMb09X/Iai/6Kh8ZxrwmFAdveFG/t2fqmNAbLWiO0TPxXZr1wU4nA8gP2wl1bRtcc+TvGXS5lnxFPio4CmCYcLvJ8UD16eHpq17h7tsBqlGlbKegi/3YQ8ME95rp74g8e2j728KwdTMCbAReo="
      - secure: "a1KSQmkwqyNx/BmIUPIBR8tUOYFzFNqI4BHx6/GK9T04s9mxiNcFXDuD7J3w7+wUmGmJaGfsfosZSgIujEMTZ9Jsz9GZu9ajIJUnNq4/mZwp8XrrVt6CCDqPAGq70rRTIcKKRsflwHdGtTLdqx8WfVFntsFbwhyavFcUzQw5ua0="
      - secure: "qmDiz0ny8l4XV29KFqXMiKDaQAd2fwURRQFnhPueuMRvoeGo0j1N4bEtJ6Dhb8a2jqzlPpDwSBFp5QqoFQnx5o3Oektymh4cQjG9B2QyNpaK1Lt0mNWQkgJmb1SXwX8efAExDI0vMBu9U8ckPy2GjRWnK3T25jHgkNnB2ILBmyI="
      - secure: "mQsqv+AhtqUo1VJHN9qZRmX6t0wh5AHoQigt3G3wLx5bEiB1Q7ctb1t28vMzDHcJW5KIq2tkulzv2o2djY8bdCZvKW71sUH2H+GcHT58y3mbS61wZ4JxTvd2eIT50RnCtpoT7WRf8rYY0nYXWIN94FwIsagGfnkxdITU44PruhE="
      - secure: "aHJLG6QO/2OIIomhsj48jVNj4IV0i1sr1WZyrqTtLWzM7Tw6q3zCbsvj+02J/aBfjY8H8l4xiLfov7dz2vTbqjiZR8vtap9Kh+FTdyUFUSbhWLLhIIWFNjMzDbE9LyIGYUee659tQjxx6dmdfqWdhha3bR2h+fHPfW0juWEHIm8="
      - secure: "U++Iv+hrTv+HoJFpRXMTnun72J03vnG6eZp8Iv6ROQfoCCY05RVtK+/Ti2MNoMg3/zmuGCIAiaRUHbP3g381bgUJIQ2x5dWfz8RnnYz+dXFv7v+bXCkgN+Sug3r9VNejPXBKvveuJE4HN4CSaJW2eo+9bONJSwdKAIDA3IYDrJk="
      - secure: "cVhqrFY04fncVCx2hn+3z2JXdNAw9PWB+mYMG8KmOl3G6/tLjiZS05fs8bNTqWOtqGz1PxOFyEtyFJNphnjuEw6Xm65g4Wes9k10smQhGtiQM44tgRJbcbbt9bjU7/vzewZhK3CBx/VxTEzfUnZwu080t+cG1Brgc2wjDevln4Y="
      - secure: "qe4xAV72HHjOpDTk9gaoWD+cCNF71WAWl66kpygjGcOba3TvHXByDfDr+mLLhwiCECHlIvC40ajMgW/WNQ2jnGVDt1JsuYzNE3qAnwYs+SXPss/ueNg8vx3j08l0tdo/D8sVFyUtKG+wjM3LubD0dDVurEFfQp1/eDl0bQuzM/U="
      - secure: "im/sA70FqlezSZeuXXnPq1sgVJ3UMna9Jh/gj+4hYxZqtVTRy330NrbC1xrVgIUBlmTvt3LfgBEfsTFlOYtLC57KTWxtI57U+o+Na/+FtIwfS68zZZI8mrxGzGTGhftnq/xsO207buimH/mwxwmlg1Mpc82G01Vl+eh2q2jKK9o="
      - secure: "N/2ePHi7OD5pnSquLyHtHftKNgBPzHdZNEJ79uTyvafhUEAkGfDgImzQotk2PywiYPw4nlHVjQL9Oe91vqIhOz7ZoVbjM7MrPte8yeB7RVHlvzWt2OBh6uynmRsnYGXSDrgLCHe0avLsIOXrE5gY3dW5NGscnJsjD2++Bf8IU+c="
      - secure: "hybNY26g/THDAHtGimmRz9SQ1fAIJSPVaNWtM//D4MBpmMe5q+xAMxpfzVT6mettI8F1T4qyZlkcFGzC1qDU0zQ+4heTS6to1gwqBRg2MCgQKT1sN990QXnW1beIklVaMIoLkfARAofB83uh9fV63xecq2oHsCKF7jVBFEAiRvY="
      - secure: "h8psVr4evt21HfcisZnqS8x48m9E4PZkkzqhTb60h0DQJQ9Nvv23a20pw96OyTlCutf00D0hczJ2Bd7bdp+2XsX6EaN2rJ/GyBl7dyUrAmf2sIyJLyha+QKKoq124kJ5WkFlB9nqdjXfogxd+v4N5aL806gwim82oQmU/O01dc8="
      - secure: "bhWfCJpz90VpI/gL0Svxrd5OlLSiy/Mcdw53jeihTT8CuHeu0IJNI0bvoeReSq490GQe5SpHVXBLw/daqROZuNlwKkCqh8zwjnIlDO4mC/5d1/j8UrRxGUeklc5ASn3y8f0fkPrdAd8APNa0xxTtcqtwm67Jojb2DtCXdb5f5X8="
      - secure: "LfIPLdJRQye1Cxh056aXAd/OJ8up3dn/FOp6PkgYqdfESHhg6SrmC0twF+5BCxomuCn5VtkC7Ez6c9kjenFpMTw8rZ/EGndBrWWjXgBEmAU+fSYGs6Z4RcFGA0fA50rHrOInDEKoeA3rM2pTzj5LiwOIFTY6ZNqmN+AyEecjNd4="
      - secure: "dBHJFkGPJ9hAno1CC/vyTaCBt6uMuNfN49oWkO/r/Xd+roQ7QC+aMyxLZbJmg+QDCFXcRyW671poMMPCHZnQzOhuUXeRGa2h2X2Tab9rzB0P6bU126Jg3c9MjoYdgVB+wK2jO80okVZrsY+VldMOGyUSQeW1ErlmlGo5oCyZJuo="
      - secure: "QpoAmtOU3KsC/CUAtwnRSwGhRgeagzZwA/Xo1hYZ5I5O+iL9cVsB7PqJj/yBvtgPbwFN7B89JdlqD73U3fimf9DglL72S97rSQXm6+mLSpFCrsY0FyjgrZyiODwbCsUG1/Rfc6Sr/n/M3PRYsNxpHXGGvWaOJT33IWXND9m+V84="
      - secure: "F0iD6FmGwrch8Iz/fVbe7HD7K5+jJSQ2S2l0XhRH+W762eo+Gnj+0fQegjs8zZFa6oXZPxn4Ee46Fqd/munkLPOGmguu/py2B/kcS58n2uEFsa44vyY85sFxDwM5xMRi3JBV45wHLaIzocsUktIqyxp20qhHmb3xDPIHew08/2Y="



