language: node_js
node_js:
   - "0.8"
before_install:
   - "npm install -g hexo"
   - "ls"
   - "hexo version"
before_script:
   - git config --global user.name "shuenhoy"
   - git config --global user.email "shuenhoy@gmail.com"
   - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
   - "curl -o /usr/lib/node_modules/hexo/lib/model.js https://gist.github.com/Shuenhoy/6039360/raw/ab01e9aaa61f6db5639967b3db1b668504906678/model.js"
   - "curl -o /usr/lib/node_modules/hexo/lib/ChinesePY.js https://gist.github.com/Shuenhoy/6039380/raw/d935a140e3f1dcd8b1ea2f526fac71b43fa72412/ChinesePY"
   - "curl -o /usr/lib/node_modules/hexo/lib/plugins/deployer https://gist.github.com/Shuenhoy/6039407/raw/26785b478179d6b45ca2854629431f3cdeb1f9a4/github.js"
   - "hexo generate"

after_script:
   - "hexo deploy" 
env:
   global:
      - REPO="git@github.com:shuenhoy/blog_source"
      - secure: "acgF9KnUwsle2GamAUoBM62EaCKKWDENj+o1XHZM29V6uGMSlSim/u7nHjAJL+FlqQ2EBa0oSegWP14G4tSQ/otowR6913t6U/tuqDhd2fjKrG9o1jPmiwhFWKQ/QYCkHurdVKNqZh/QnAXp0ANnvUuOEmMfCg4Ni/wg0CcAnI0="
      - secure: "TXeBHxngGLe/Zlw5G4j/RKSVOvFMsehSOpftE8ivBeJbcBLCpLoLl2TGJDto2sW8pQo3J0RCBGB/a6qsCuxng5oDCwEeiI2wALbhci0ny/zbi2ge2MSVR6LTAwJA0w6JPPpAcKdgFohFUDFu28pbRpJREtLK9e18YsFc1bqWT24="
      - secure: "Gk3ZYDs32h1bKld8tbzXur1v3Aql+MIIE03QTy5sHO7NHtPqpJfxoWfOZdjI98xUF6qIMy2aJU4SWmW73H+RvzYUcIZJq+ohHCB1xDRZfT6/KGILIsQWYCYHx5iGbObv+URUOt+QlZcFwPAw+4A8EwnX/rix7v1scvSwj7RF4Po="
      - secure: "fGufItogKPbI5eJEINMah2UsvAkFjwbXQUtvNtpXUgKUMLxU84Ob2SNu6lr/mBTN/b9yMH0gUdqWZqNnsg6swapv3euj5X0PlGME96MDywnCZN6O6B0B2eFTGwnBSVzFSMtDHa96ZakIqsm0xclyg9P8Vfe2JrH/cjiTa7dSfXo="
      - secure: "gwLI2LBP61Sgh7dwQG+MsgPDUpCU/TuS/WMuUqYnM1n/WwudngYGM7xW3+VZwitAL+627Zvxn9FYXGY199g7gF9OhI9uk0i1Uc0exUxap0231IevEC+BNEvLYv4Qz9bajhI9iEzSle3JwZUGOuQRb6UFvOImkQR+DHM6jHwv9m4="
      - secure: "Bb8RAIRclHbaI+yO9IV1i4oN4Seyrs5pR7qUg7w0iLZkZL5I+Cx6/uzWG/tlraPCxm4/q8+fmixVtdiB/90HG12sPB8goAJ4HGG0qgKlI8YjGzOlcJhkADyaTPJ7khBB1lMsV3kWqPX6tNqHNWPswVciNbB6R4yW6oyv/q8GoyA="
      - secure: "j7DYdlQGT0whTaFAjUT23KkGPomDk8ghuaVwSNxfaSZBzv7qp0HYcelx7fbB4WPoaKO1TO3HuZYus6/bBZVTRJUCewnHilCRXe/J2l7yj0IcRgAEubNBY8HPjWgZuUf1tvjBxi1TAtrI+/H7YKKN44AzXVkdwHRUZumU7Ne1+Oo="
      - secure: "bxkkxTDtUJ2+5TBUwBoAWmORuOPbGMBgzEmxnIrwVlq9bEQO2vfWkYfQhY5WGQGaxLRa624GHiPFHmvVohsQEyda3iKhAETTiqWmpf1FrErzyXQaYO5ic3XrPycu4qhgbIpXFDq4LCY8OfQQKVRZWG9ZHXk5sXHn8DfjR4Hr8YE="
      - secure: "c9HIrVdz/KS5PNJzb8VO1Sx/V/54OChesyK8ztIa1uoVUgLCayEEvu/DQcz1nTEZRbp12AFaU92WXUn43NRWLH1yo0vGYxFlN9Z6Di8Vwf4fGLI3kJJIWFEpsji5NpVJvaXL0+oQI0QtjcSEswVV/NS25aHH30BhyBUcIPvnrvQ="
      - secure: "ZyFA2LTSSK6JCjZv1Xr/GRsBr5twat5n2Rki6PHK1PM9iurTBHdsfO8udhVnj4BfDAchlcDJcPrZ3hP4nHZIYac6AV4klwrp0bjNoMdiAhYQKpiLcuapOKjMOyrCxLrjcpjNamWbsegmvagHiMNX6p7jbrTamaqgmpt62iGmb8s="
      - secure: "NfK2hVC7WzLSq3DBq6djZqoQF1GSR4oBx0padg+l+HivDzRd6vyZ4tXKl/siTmQmXbQMr1tztp50hhTryJK608OaC9Elhmo4/hRZfiUTaNIYqieGjJHwv7t78nXxTv5YL3JNSUxaaKkQBAdOo5Il0P6ej9WafqiNrmuTNhuAqr8="
      - secure: "f3GXb9IUqvTL6A0q1zARs60FHXAjN4cT08EbcmEd+2C7RbwgRelCIO/8OBWQgqFYIvmd9fi6byl0IXb2zaCugOTu2hnPY5RNIZ7TGL3Jrwijoi4Qd5V1Hpa4G+ECcf5fvMSghUs8EG6zeqC5fFgA7hC7iOhiq4A/QrrcQqzsawY="
      - secure: "PR0rsscadBRYplmAs4PVvKWffmHsqBTI/rgPqS7lCZWUIrev6jsxTxLOKTxJRUAV9h3uCzt/LA2Hwb+cB9fLYZXnCdlQyOMm7NIgyJ+UHwDwhkrDG4hhkU/twVrSChA+sfQf+zNQ7Q/Vl5GeUqnOg1TU4xkezLSWL5TrT3qSZQ4="
      - secure: "Urtw94sD8qrIARoR69FKX/dqJel49NRrya9hTH33Qg3gzXWt7gcQZrQtYG6PeE+Egn2Caw4+L4O4VGBCmgwUapzhlREGkElOgw/Ccc6opfryehHkce9+yC3Pjbw8AvhHlbbN8tY71w00YM1gO5SmN0IbAbed1ukycugTUrN3rYE="
      - secure: "DnyEyjic2BhAh6yllhW3zQOYSonmCLFQQFNwNaeAzNtf9SY8ofmhU22h+AWWkdHJz8ukAnrGzmfUUEJ3A5XlLWOTF94nVpqaks6WBXdq7amyormcZu60VjDa3WbhvNE+L7GM/fKisGcK6JNt5XAhs51hB2vSwgj2GHigcLgtGcM="
      - secure: "Hf4rmFABxpfjAGMz7IOX2ify/9Wx8qtugLScAVF5QK7KuNmFo8MEVr0+UIlmuM2DaD/Slm8FPv/h/F1fJk08DgBeHYIuvdkBZ7oN81oMlD2XAZR3TDZv7O4JMcWLCXyPRit0OJce32rHYCPFfEjmdbPmn0v6ETDXr1qMFFQhsXw="
      - secure: "d0FwZYYPTsJI6hOr9b0MA58z7JxG5r0jjeZmkDKV+3+Od3b8pStCiSiwolMTjyoWUI4/hvpVxwVUPEJgyaWdiQyOLwdbqonbF1M6O43EedvTHVMuWVm4PeP9/si7wRzWU5zCdDUIK0gHTpY+C/cBdJmEamy58xz/pzkyVLYyA9Q="
      - secure: "iXvLYuIFwv/wjiNQo6KpQsX7LuryLUA5uKcDzzTrJhnOAMo8ZxN7kqngziy31kyUGCzjW50Z2zuxsXBNgvkymUNmOVS4MeJMUex6QAs7Z2jbuLwPdVfCGF1T5PPXMzwsv83nKl6oGtLgn1CFO/qbCYK2m+fklwbyBsxeNVbhQBo="
      - secure: "DMOYm1vk47U16knRgO+q9ownouS9KRCCqP3aBl9aNwO1Sbvn9YeqxkRQ5n/lLL+kG8Ko3UaOiybOOuB7Uzg2Wj86fBzbv9yH/GllgT04m/QGk8xWaXc23yxG48fVyInj6CqjSFXZiK6lsqZk9rJc4zUqLw65VrfhyuBodm0K1rE="
      - secure: "dlqSjGtp5fucNbMJXk+x1X2hLC2bB3wnDYjG/hv2IS2ef8m4TcbggPuE9iwo2Sk6RDYOLJh+xW13sV5r6XCQAxaDGRhrL86rlfWBSj3VV4Pl5xjaYQzmyLXnf5sG209wLbRpMHqNuIk2mmAFDgRDKBn9aba5dJr9pOM2QPbfKH4="
      - secure: "TTl6i8lk1lfhQv5teRNM5lVRZiXoM5XWxFuVlwB3F0uREww+Ij412x/MCP7hysAGaJwSbGsdC1VkUTfPVMRcpJBSPUj9BoTGm6gj08y6FQTwkjaRE9CKfpG9SiP2L1kO2nzY7643NcG+FgaxbhBNys6l+e9cYYjdOagcjfvGhkw="
      - secure: "jRMz+bE6vBGMGvDfMUT9/SpYsXuSrJNWvabPwiEmbIys1UHFNnkhxxUZNB3ldUpOtj3Alo3zh9wzPCEloWPhr+DLMxWx2Vn0mzLFIeIFVKF2Xa3T2pM6RPfj/FWLzFeRQCg19dGOwYV43HA5+bKAmFSQi0ycpVabsaCtxQgvqgc="
      - secure: "COIe7ijF5RzcY0lWLbhG6WKLvgPwVlchw01iG43K3rH7oQcv+DOgrOQVp7beAUVDFqSgGLgWypR7OPZOwEkxv+u0Tt9Ox2C+PFultmH9Z2mEYGKYejPoQIp6ne6qXUbeHh5OIB5XQyQfDyifG4INt+6MR/ERvuAQR+GYxZDFm+g="


